on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - main
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: thygesteffensen
  GIT_AUTHOR_EMAIL: 31892312+thygesteffensen@users.noreply.github.com
  CI_NUGET_API_KEY: ${{ secrets.CI_NUGET_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Building and testing
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json

      - name: Cleaning
        run: dotnet clean -c Release

      - name: Build solution
        run: dotnet build -c Release

      - name: Test solution
        run: dotnet test -c Release --no-build --verbosity normal

  release:
    name: Releasing
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows

      - name: Add plugin for executing bash commands
        run: npm install @semantic-release/exec -D
        working-directory: ./.github/workflows

      - name: Dry Run Semantic to get next version number
        working-directory: ./.github/workflows
        run: npx semantic-release --dry-run --no-ci

      - name: Cleaning
        run: dotnet clean --configuration Release

      - name: Package Compo
        run: dotnet pack -c Release -p:PackageVersion=${RELEASE_VERSION} -o ./artifacts
        if: ${{ env.RELEASE_VERSION }}

      - name: Release to GitHub and NuGet
        working-directory: ./.github/workflows
        run: npx semantic-release
